site_name: 'python-app'
site_description: 'Main documentation for python-app'
repo_url: https://github.com/anthony-gilbert/python-app
site_author: 'Anthony Gilbert'
edit_uri: edit/master/docs

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'docs/index.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started: 'docs/index.md'