name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - master


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set short git commit SHA
        shell: bash
        run: |
          echo "COMMIT_SHA=${GITHUB_SHA:0:6}" >> $GITHUB_ENV
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: anthonygilbertt/python-app:${{env.COMMIT_SHA}}
  cd:
    runs-on: self-hosted
    needs: ci
    steps:
      - name: Install ArgoCD CLI
        shell: bash
        run: |
          curl -ksSL -o argocd https://argo-argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv .argocd /usr/local/bin/argocd
          echo "ArgoCD CLI installed successfully."
        
        
      - name: ArgoCD sync
        shell: bash
        run: | 
          argocd login argo-argocd-server.argocd --insecure --username admin --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app
          echo "ArgoCD login completed successfully."
        # env:
        #   ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
        #   ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
